In [ ]:
import tensorflow as tf
tf.InteractiveSession()

In [ ]:
a = tf.zeros(2)
a.eval()

array([0., 0.], dtype=float32)

In [ ]:
b = tf.ones((2,3))
b.eval()


array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [ ]:
c = tf.fill((4,3), value=3.2)
c.eval()

array([[3.2, 3.2, 3.2],
       [3.2, 3.2, 3.2],
       [3.2, 3.2, 3.2],
       [3.2, 3.2, 3.2]], dtype=float32)

In [ ]:
a = tf.constant(3)
a.eval()

3

In [ ]:
a = tf.random_normal((3,3), mean = 0, stddev = 1)
a.eval()

array([[-0.889472  ,  0.0844826 , -0.30721888],
       [-0.5375742 ,  0.36548775,  1.7699789 ],
       [-0.81044394,  0.7252283 ,  0.21359485]], dtype=float32)

In [ ]:
b = tf.truncated_normal((2,2), mean=0, stddev=2)
b.eval()

array([[2.9228816, 2.4135451],
       [1.0338631, 1.5506045]], dtype=float32)

In [ ]:
u = tf.random_uniform((4,4), minval=0, maxval=4)
u.eval()

array([[0.56864023, 1.4896016 , 0.41747808, 2.1328754 ],
       [2.7821808 , 0.7568073 , 2.7148619 , 1.0112348 ],
       [1.3655252 , 1.8308392 , 1.8543782 , 0.82537794],
       [1.4474301 , 3.9753623 , 2.36659   , 0.8141947 ]], dtype=float32)

In [ ]:
x = tf.ones((2,2))
y = tf.ones((2,2))
z = x+y
z.eval()
print(z)
z2 = 2*z
z2.eval()

Tensor("add:0", shape=(2, 2), dtype=float32)


array([[4., 4.],
       [4., 4.]], dtype=float32)

In [ ]:
i = tf.eye(5)
i.eval()

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]], dtype=float32)

In [ ]:
r = tf.range(5,11,1)
d = tf.diag(r)
d.eval()

array([[ 5,  0,  0,  0,  0,  0],
       [ 0,  6,  0,  0,  0,  0],
       [ 0,  0,  7,  0,  0,  0],
       [ 0,  0,  0,  8,  0,  0],
       [ 0,  0,  0,  0,  9,  0],
       [ 0,  0,  0,  0,  0, 10]], dtype=int32)

In [ ]:
e = tf.matrix_transpose(d+tf.fill((6,6), value = 2))
e.eval()

array([[ 7,  2,  2,  2,  2,  2],
       [ 2,  8,  2,  2,  2,  2],
       [ 2,  2,  9,  2,  2,  2],
       [ 2,  2,  2, 10,  2,  2],
       [ 2,  2,  2,  2, 11,  2],
       [ 2,  2,  2,  2,  2, 12]], dtype=int32)

In [ ]:
f = tf.matmul(d,e)
f.eval()

array([[ 35,  10,  10,  10,  10,  10],
       [ 12,  48,  12,  12,  12,  12],
       [ 14,  14,  63,  14,  14,  14],
       [ 16,  16,  16,  80,  16,  16],
       [ 18,  18,  18,  18,  99,  18],
       [ 20,  20,  20,  20,  20, 120]], dtype=int32)

In [ ]:
g = tf.to_float(f)
g.eval()

Instructions for updating:
Use tf.cast instead.


array([[ 35.,  10.,  10.,  10.,  10.,  10.],
       [ 12.,  48.,  12.,  12.,  12.,  12.],
       [ 14.,  14.,  63.,  14.,  14.,  14.],
       [ 16.,  16.,  16.,  80.,  16.,  16.],
       [ 18.,  18.,  18.,  18.,  99.,  18.],
       [ 20.,  20.,  20.,  20.,  20., 120.]], dtype=float32)

In [ ]:
h = tf.reshape(g, (12,3))
h.eval()

array([[ 35.,  10.,  10.],
       [ 10.,  10.,  10.],
       [ 12.,  48.,  12.],
       [ 12.,  12.,  12.],
       [ 14.,  14.,  63.],
       [ 14.,  14.,  14.],
       [ 16.,  16.,  16.],
       [ 80.,  16.,  16.],
       [ 18.,  18.,  18.],
       [ 18.,  99.,  18.],
       [ 20.,  20.,  20.],
       [ 20.,  20., 120.]], dtype=float32)

In [ ]:
h.get_shape()

TensorShape([Dimension(12), Dimension(3)])

In [ ]:
j = tf.expand_dims(h,1)
j.eval()

array([[[ 35.,  10.,  10.]],

       [[ 10.,  10.,  10.]],

       [[ 12.,  48.,  12.]],

       [[ 12.,  12.,  12.]],

       [[ 14.,  14.,  63.]],

       [[ 14.,  14.,  14.]],

       [[ 16.,  16.,  16.]],

       [[ 80.,  16.,  16.]],

       [[ 18.,  18.,  18.]],

       [[ 18.,  99.,  18.]],

       [[ 20.,  20.,  20.]],

       [[ 20.,  20., 120.]]], dtype=float32)

In [ ]:
j.get_shape()

TensorShape([Dimension(12), Dimension(1), Dimension(3)])

In [ ]:
k = tf.to_int32(j)
k.eval()

Instructions for updating:
Use tf.cast instead.


array([[[ 35,  10,  10]],

       [[ 10,  10,  10]],

       [[ 12,  48,  12]],

       [[ 12,  12,  12]],

       [[ 14,  14,  63]],

       [[ 14,  14,  14]],

       [[ 16,  16,  16]],

       [[ 80,  16,  16]],

       [[ 18,  18,  18]],

       [[ 18,  99,  18]],

       [[ 20,  20,  20]],

       [[ 20,  20, 120]]], dtype=int32)

In [ ]:
l = tf.squeeze(k)
l.eval()

array([[ 35,  10,  10],
       [ 10,  10,  10],
       [ 12,  48,  12],
       [ 12,  12,  12],
       [ 14,  14,  63],
       [ 14,  14,  14],
       [ 16,  16,  16],
       [ 80,  16,  16],
       [ 18,  18,  18],
       [ 18,  99,  18],
       [ 20,  20,  20],
       [ 20,  20, 120]], dtype=int32)

In [ ]:
m = tf.range(0,6,2)
m.eval()

array([0, 2, 4], dtype=int32)

In [ ]:
m = tf.to_float(m)
m.eval()

array([0., 2., 4.], dtype=float32)

In [ ]:
n = tf.to_int32(m)+l
n.eval()

array([[ 35,  12,  14],
       [ 10,  12,  14],
       [ 12,  50,  16],
       [ 12,  14,  16],
       [ 14,  16,  67],
       [ 14,  16,  18],
       [ 16,  18,  20],
       [ 80,  18,  20],
       [ 18,  20,  22],
       [ 18, 101,  22],
       [ 20,  22,  24],
       [ 20,  22, 124]], dtype=int32)

In [ ]:
sess = tf.Session()
b = tf.ones((2,2))
b.eval(session=sess)

array([[1., 1.],
       [1., 1.]], dtype=float32)

In [ ]:
b.eval()

array([[1., 1.],
       [1., 1.]], dtype=float32)

In [ ]:
tf.get_default_graph()

In [ ]:
a = tf.Variable(tf.zeros((2,2)))

Instructions for updating:
Colocations handled automatically by placer.


In [ ]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())
a.eval(session=sess)

array([[0., 0.],
       [0., 0.]], dtype=float32)

In [ ]:
sess.run(a.assign(tf.ones((2,2))))
a.eval(session=sess)

array([[1., 1.],
       [1., 1.]], dtype=float32)